/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logica.BotonTablaPeriodica;
import java.awt.Button;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SSDesth
 */
public class frmTablaPeriodica extends javax.swing.JFrame {

    // es [alto][ancho]
    private BotonTablaPeriodica[][] MatrizBotones1 = new BotonTablaPeriodica[7][18];
    private BotonTablaPeriodica[][] MatrizBotones2 = new BotonTablaPeriodica[2][15];
    
    /**
     * Creates new form frmTablaPeriodica
     */
    public frmTablaPeriodica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMatriz1 = new javax.swing.JPanel();
        lblMatriz1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMatriz2 = new javax.swing.JPanel();
        lblMatriz2 = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMatriz1.setBackground(new java.awt.Color(255, 255, 255));

        lblMatriz1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Fondos/M1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMatriz1Layout = new javax.swing.GroupLayout(jPanelMatriz1);
        jPanelMatriz1.setLayout(jPanelMatriz1Layout);
        jPanelMatriz1Layout.setHorizontalGroup(
            jPanelMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelMatriz1Layout.setVerticalGroup(
            jPanelMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabla Periodica");

        jPanelMatriz2.setBackground(new java.awt.Color(255, 255, 255));

        lblMatriz2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Fondos/M2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMatriz2Layout = new javax.swing.GroupLayout(jPanelMatriz2);
        jPanelMatriz2.setLayout(jPanelMatriz2Layout);
        jPanelMatriz2Layout.setHorizontalGroup(
            jPanelMatriz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMatriz2Layout.setVerticalGroup(
            jPanelMatriz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriz2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelInfo.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelMatriz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jPanelMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTablaPeriodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTablaPeriodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTablaPeriodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTablaPeriodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTablaPeriodica().setVisible(true);
            }
        });
    }

    public void GeneradorDeBotones() {

        int anchoYAlto = 50;
        int numeroBoton = 1;
        boolean agregarBoton = true;

        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 18; j++) {
                if (i == 0) {
                    if (j > 0 && j < 17) {
                        
                        MatrizBotones1[i][j] = null;
                        agregarBoton=false;
                    }
                }
                if (i == 1 || i == 2) {
                    if (j > 1 && j < 12) {
                        MatrizBotones1[i][j] = null;
                        agregarBoton=false;
                    }
                }
                if (i == 5 || i == 6) {
                    if (j == 2) {
                        MatrizBotones1[i][j] = null;
                        int y = 0;
                        if (i == 6) {
                            y = 1;
                        }
                        for (int x = 0; x < 15; x++) {
                            agregarBoton=false;
                            MatrizBotones2[y][x]
                                    = new BotonTablaPeriodica(anchoYAlto * x,
                                    anchoYAlto * y, anchoYAlto, anchoYAlto,
                                    numeroBoton);
                            jPanelMatriz2.add(MatrizBotones2[y][x]);
                            numeroBoton++;
                        }
                    }
                }
                if (agregarBoton) {
   
                    MatrizBotones1[i][j] = new BotonTablaPeriodica(anchoYAlto * j,
                            anchoYAlto * i, anchoYAlto, anchoYAlto, numeroBoton);
                    jPanelMatriz1.add(MatrizBotones1[i][j]);
                    numeroBoton++;

                }
                agregarBoton=true;
                //MatrizBotones1

            }
        }

    }
    
    public void CargarImagenes(){
       /* 
        ImageIcon imagen = new ImageIcon("src/mulimedia/Fondos/M1.Png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblMatriz1.getWidth(),
                lblMatriz1.getHeight(), Image.SCALE_DEFAULT));
        lblMatriz1.setIcon(icono);
    */
    
    }
    
    public void MostrarElemento(int Entrada){
        JOptionPane.showMessageDialog(this,"Hola soy el elemento: "+Entrada);
    
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMatriz1;
    private javax.swing.JPanel jPanelMatriz2;
    private javax.swing.JLabel lblMatriz1;
    private javax.swing.JLabel lblMatriz2;
    // End of variables declaration//GEN-END:variables
}
